# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-18 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_exam_app', '0002_item_likecount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='likeCount',
            field=models.IntegerField(default=1),
        ),
    ]
